if (MAKE_MAN)
	set(MANPAGE_SRC_FILE ${PROJECT_SOURCE_DIR}/doc/${PROJECT_NAME}.1.md)
	set(MANPAGE_OUT_FILE ${PROJECT_BINARY_DIR}/${PROJECT_NAME}.1)
	set(MANPAGE_OUT_FILE_GZ ${MANPAGE_OUT_FILE}.gz)

	find_program(PANDOC pandoc REQUIRED)
	find_program(GZIP   gzip   REQUIRED)

	add_custom_command(
		OUTPUT ${MANPAGE_OUT_FILE_GZ}
		COMMAND ${PANDOC} -s -t man ${MANPAGE_SRC_FILE} -o ${MANPAGE_OUT_FILE}
		COMMAND ${GZIP} -f ${MANPAGE_OUT_FILE}
		DEPENDS ${MANPAGE_SRC_FILE}
	)

	add_custom_target(manual ALL DEPENDS ${MANPAGE_OUT_FILE_GZ})
endif()
